### ISSUE TITLE
Bug on DellFanKeepAlive.

### ISSUE THREAD

**Issue by echomokona** [AaronKelley/DellFanManagement#1]
OS: Windows 10 LTSC 1809 x64.
Model: Dell Inspiron 7588.
Running elevated.

``` 
D:\f\dellfancmd>dellfankeepalive
Error: Index was outside the bounds of the array.
   at DellFanManagement.KeepAlive.DellFanKeepAlive.Main(String[] args)

D:\f\dellfancmd>dellfankeepalive /?
Error: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DellFanManagement.KeepAlive.DellFanKeepAlive.Main(String[] args)

D:\f\dellfancmd>
```

Fresh download of latest release; downloaded all zips and extracted them to same directory.

**Comment by AaronKelley** [comment]
See: http://forum.notebookreview.com/threads/dellfanmanagement-dellfankeepalive-%E2%80%93-tools-for-managing-the-fan-speed-in-dell-laptops.833340/
This program expects three command-line parameters: lower temperature threshold, upper temperature threshold, and fan RPM threshold.  I will update it to properly complain if you don't give proper parameters, rather than error out.
