### ISSUE TITLE
Fan control cannot be manipulated on Dell laptop models released in 2021 or later

### ISSUE THREAD

**Issue by vlakoff** [AaronKelley/DellFanManagement#14]
Hello,

I cannot disable EC on this laptop: Dell Latitude 5320 2-in-1, i7-1185G7, Windows 10 64-bit.

No errors are displayed, it just doesn't take control of the fan.

```
> DellFanCmd.exe test

Loading SMM I/O driver...
 ...Success.
Disabling EC fan control...
Looks like fan 2 is not present, system only has one fan?
Measuring: Fan 1, level 0...
Measuring: Fan 1, level 1...
Measuring: Fan 1, level 2...
Enabling EC fan control...
Test procedure is finished.


Fan 1 initial speed: 4294967295

Fan 1 level 0 speed: 4294967295
Fan 1 level 1 speed: 4294967295
Fan 1 level 2 speed: 4294967295

Unloading SMM I/O driver...
 ...Done.
```

Note the strange value `4294967295` (which is the maximum 32-bit **unsigned** integer). Refs [Wikipedia](https://en.wikipedia.org/wiki/4,294,967,295#In_computing).

For instance, that value triggers a bug with the following command:

```
> DellFanCmd.exe rpm-fan1

Loading SMM I/O driver...
 ...Success.
Attempting to query the fan RPM...
 Result: 4294967295
Error: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DellFanManagement.Cmd.DellFanCmd.Main(String[] args)
Unloading SMM I/O driver...
 ...Done.
```

SpeedFan lacks support:
* In "Configure > Temperatures", the "Pwn1" Sensors are missing
* In "Configure > Fans", there is no fan
* In "Configure > Options", I checked the "Enable DELL support" checkbox, but after I open "Options" again the checkbox got unchecked

HWiNFO doesn't detect the EC controller (the "fan icon" to control the fan speed is missing).

For the record, DellFanManagement works as expected on two other laptops:
* Dell Latitude 5310 2-in-1, i5-10310U (the laptop generation just before)
* Dell Latitude E7270, i5-6300U

I would be more than willing to provide all the debug info you need.

I really hope something can be done about this…

Regards

**Comment by AaronKelley** [comment]
11th gen systems are not supported at this time.  Dell has changed the BIOS interface for fan control, and I haven't been able to figure out new fan control mechanism (nor has anyone else AFAIK).  I do have capability to read the fan RPM (in the current committed code but not in the published 2.x version).

**Comment by vlakoff** [comment]
It seems you were already aware of this issue.
Are the HWiNFO devs aware about it? I didn't find posts specifically about 11th Gen on their forum.

Can I hope a solution will be found?

**Comment by AaronKelley** [comment]
I made a post on their forum detailing how to read RPM values (and temperatures) with the new setup.  It didn't get any attention.  https://www.hwinfo.com/forum/threads/new-dell-systems-ec-sensor-values-not-available-fix.7482/

**Comment by AaronKelley** [comment]
I'm going to pin this issue and leave it open as a sort of "catch-all" for 11th gen (and up) support.  I currently don't have any leads on being able to provide this support, but if anyone runs into other apps or solutions that are able to offer fan control on these newer systems, I'd be happy to take a look and see if it can be adapted for use here.  (This would even include solutions specific to Linux.)

**Comment by vlakoff** [comment]
Thanks for taking care of this situation. For the record, I'm considering to sell back my Latitude 5320, it has too many regressions over the 5310 (for instance, that new touchpad without separated buttons is a disaster), and the fan control is a deal breaker.

I'm afraid the fan control won't be implemented in a foreseeable future, for this family of Intel CPUs, and for the next ones…

By any chance, do you know the situation with other laptop brands, and with AMD CPUs? Do they have solutions to configure fan speed like we do here, are there brands known for letting control fan speed?

**Comment by AaronKelley** [comment]
You can look at tools like SpeedFan, HWiNFO64, and [NoteBook FanControl](https://github.com/hirschmann/nbfc) which can control fans in a number of different systems.  My knowledge in the area is basically specific to Dell laptops because that's all that I have used for years.  However, I think there is a general trend across the industry towards moving away from the traditional EC-based fan control to more custom solutions, so, each one will probably require a unique solution to enable manual control.

(Some laptops manufacturers might actually provide their own tools for this.  For example, newer Alienware can get some granular fan control options right through Alienware Command Center.)

The [NotebookReview](http://forum.notebookreview.com/) forums might be a good resource; they have "sections" dedicated to different laptop manufacturers and often have threads specific to certain models.  You could ask and get input from users of those systems to see if they have experimented with fan control or if the fan behavior on these systems might be adequate without manual control.

**Comment by techjaw** [comment]
Hello and, above all, thank you for the great work you have shared with us on various forums. Like you, I have been a supporter of Dell for over a dozen years, mainly XPS (the best equipment I have ever had), and now I have a Vostro 5630 and the behavior of the fans is unacceptable, especially on battery power. I have been an IT specialist for 25 years, but I gave up when it comes to controlling fans in 13th generation Dells. Additionally, the 1360P doesn't quite cope with thermals. So the question for you is whether you have a way to control the fan in any way. I've probably tested everything that could help. I limited the power and clock speed to a minimum so that the battery wouldn't make too much noise. Of course, new toothpaste, etc. I came to the conclusion that I can only achieve the effect in two ways. Either I will build a PWM modulator and connect it between the board and the fan (4 pins) or I will use a bus programmer and block what is needed. The warranty doesn't matter to me. Do I have any experience, documentation, links about my two ideas? Thank you in advance for any help. In desperation, I disconnected the fan for a long time, experienced silence and the temperature oscillated between 70 degrees C and a maximum of 95 degrees C. I even thought about an independent fan control system, a PWM module + thermistor powered from USB or something else. However, I have to "fool" the board that the fan is connected, but I don't know how yet.

**Comment by pmojong** [comment]
This is probably the issue I'm having as well (XPS 15 9530, 2023). Should've checked here first instead of racking my brain for hours...

**Comment by ohaya** [comment]
I ended up here because I found a reference to dellfanmanagement when I was trying to check why my Dell Vostro (about 2+ years old - it is currently December 2024 when I am posting this) was not showing a fan in Speedfan, because the laptop is having some weird behavior.

I'm seeing the same things that the OP found, and nothing seems to see the CPU fan at all (and have tried the other things also).

**Comment by rvxfahim** [comment]
I have exhausted all options and also in a state where I cannot control any fan of the dell precision 7680 (2025). Dell Optimizer application have an option for ultra performance with high fan speed, but that still doesn't help with the hot 4090 laptop GPU because this mode also overclocks the components automatically.
